version: "3.8"

services:
  backend:
    build:
      context: ./backend-spring
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379

  frontend:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev"]
    depends_on:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--save", "", "--appendonly", "no" ]
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  redis_data:

